extern const GeoLayout castle_courtyard_area_1_geo[];
extern const GeoLayout castle_courtyard_area_1[];
extern const Collision castle_courtyard_area_1_collision[];
extern const MacroObject castle_courtyard_area_1_macro_objs[];
extern const GeoLayout castle_courtyard_area_2_geo[];
extern const GeoLayout castle_courtyard_area_2[];
extern const Collision castle_courtyard_area_2_collision[];
extern const MacroObject castle_courtyard_area_2_macro_objs[];
extern const GeoLayout castle_courtyard_area_3_geo[];
extern const GeoLayout castle_courtyard_area_3[];
extern const Collision castle_courtyard_area_3_collision[];
extern const MacroObject castle_courtyard_area_3_macro_objs[];
extern Vtx castle_courtyard_dl_WhiteRoom_mesh_vtx_0[186];
extern Gfx castle_courtyard_dl_WhiteRoom_mesh_tri_0[];
extern Vtx castle_courtyard_dl_WhiteRoom_mesh_vtx_1[54];
extern Gfx castle_courtyard_dl_WhiteRoom_mesh_tri_1[];
extern Vtx castle_courtyard_dl_WhiteRoom_003_mesh_vtx_0[186];
extern Gfx castle_courtyard_dl_WhiteRoom_003_mesh_tri_0[];
extern Vtx castle_courtyard_dl_WhiteRoom_003_mesh_vtx_1[54];
extern Gfx castle_courtyard_dl_WhiteRoom_003_mesh_tri_1[];
extern Vtx castle_courtyard_dl_WhiteRoom_006_mesh_vtx_0[186];
extern Gfx castle_courtyard_dl_WhiteRoom_006_mesh_tri_0[];
extern Vtx castle_courtyard_dl_WhiteRoom_006_mesh_vtx_1[54];
extern Gfx castle_courtyard_dl_WhiteRoom_006_mesh_tri_1[];

extern Gfx castle_courtyard_dl_WhiteRoom_mesh[];
extern Gfx castle_courtyard_dl_WhiteRoom_003_mesh[];
extern Gfx castle_courtyard_dl_WhiteRoom_006_mesh[];
extern Gfx castle_courtyard_dl_material_revert_render_settings[];

