const GeoLayout palmtree_geo[] = {
	//GEO_NODE_START(),
	GEO_CULLING_RADIUS(0x800),
	GEO_OPEN_NODE(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, palmtree_000_DL_Base_mesh),
			GEO_DISPLAY_LIST(1, palmtree_000_DL_Leaves_mesh),
			GEO_DISPLAY_LIST(6, palmtree_000_DL_Shadow_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, palmtree_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, palmtree_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
