#include "src/game/envfx_snow.h"

const GeoLayout jrb_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, jrb_dl_Room1C_geo),
			GEO_BRANCH(1, jrb_dl_Room2C_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_dl_Room1C_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE_WITH_DL(1, -585, 4719, 15995, 0, 0, 0, jrb_dl_MetalSlide_mesh),
			GEO_TRANSLATE_ROTATE_WITH_DL(1, -18447, -10678, 23443, 0, 0, 0, jrb_dl_MetalSlide_001_mesh),
			GEO_TRANSLATE_ROTATE_WITH_DL(6, -12326, 13386, 12637, 0, 0, 0, jrb_dl_MetalSlide_003_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_dl_Room2C_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, -15000, 0, 0, 0, 0, jrb_dl_DeathPlane_001_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -500, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_enfvx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, jrb_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
