extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Vtx ccm_dl_Arena_mesh_vtx_0[44];
extern Gfx ccm_dl_Arena_mesh_tri_0[];
extern Vtx ccm_dl_ArenaRedCircle_001_mesh_vtx_0[40];
extern Gfx ccm_dl_ArenaRedCircle_001_mesh_tri_0[];
extern Vtx ccm_dl_Chain_001_mesh_vtx_0[32];
extern Gfx ccm_dl_Chain_001_mesh_tri_0[];
extern Vtx ccm_dl_Decal_mesh_vtx_0[48];
extern Gfx ccm_dl_Decal_mesh_tri_0[];
extern Vtx ccm_dl_Ground_mesh_vtx_0[180];
extern Gfx ccm_dl_Ground_mesh_tri_0[];
extern Vtx ccm_dl_Ground_mesh_vtx_1[115];
extern Gfx ccm_dl_Ground_mesh_tri_1[];
extern Vtx ccm_dl_Ground_mesh_vtx_2[48];
extern Gfx ccm_dl_Ground_mesh_tri_2[];
extern Vtx ccm_dl_Ground_001_mesh_vtx_0[60];
extern Gfx ccm_dl_Ground_001_mesh_tri_0[];
extern Vtx ccm_dl_Ground_001_mesh_vtx_1[12];
extern Gfx ccm_dl_Ground_001_mesh_tri_1[];
extern Vtx ccm_dl_Ground_002_mesh_vtx_0[40];
extern Gfx ccm_dl_Ground_002_mesh_tri_0[];
extern Vtx ccm_dl_Ground_003_mesh_vtx_0[12];
extern Gfx ccm_dl_Ground_003_mesh_tri_0[];
extern Vtx ccm_dl_Ground_003_mesh_vtx_1[7];
extern Gfx ccm_dl_Ground_003_mesh_tri_1[];
extern Vtx ccm_dl_Ground_005_mesh_vtx_0[40];
extern Gfx ccm_dl_Ground_005_mesh_tri_0[];
extern Vtx ccm_dl_Wood_mesh_vtx_0[24];
extern Gfx ccm_dl_Wood_mesh_tri_0[];
extern Vtx ccm_dl_Wood_001_mesh_vtx_0[24];
extern Gfx ccm_dl_Wood_001_mesh_tri_0[];
extern Vtx ccm_dl_Wood_005_mesh_vtx_0[64];
extern Gfx ccm_dl_Wood_005_mesh_tri_0[];
extern Vtx ccm_dl_Wood_006_mesh_vtx_0[64];
extern Gfx ccm_dl_Wood_006_mesh_tri_0[];
extern Vtx ccm_dl_Wood_007_mesh_vtx_0[64];
extern Gfx ccm_dl_Wood_007_mesh_tri_0[];
extern Vtx ccm_dl_Wood_008_mesh_vtx_0[64];
extern Gfx ccm_dl_Wood_008_mesh_tri_0[];
extern Vtx ccm_dl_Wood_009_mesh_vtx_0[64];
extern Gfx ccm_dl_Wood_009_mesh_tri_0[];

extern Gfx ccm_dl_Arena_mesh[];
extern Gfx ccm_dl_ArenaRedCircle_001_mesh[];
extern Gfx ccm_dl_Chain_001_mesh[];
extern Gfx ccm_dl_Decal_mesh[];
extern Gfx ccm_dl_Ground_mesh[];
extern Gfx ccm_dl_Ground_001_mesh[];
extern Gfx ccm_dl_Ground_002_mesh[];
extern Gfx ccm_dl_Ground_003_mesh[];
extern Gfx ccm_dl_Ground_005_mesh[];
extern Gfx ccm_dl_Wood_mesh[];
extern Gfx ccm_dl_Wood_001_mesh[];
extern Gfx ccm_dl_Wood_005_mesh[];
extern Gfx ccm_dl_Wood_006_mesh[];
extern Gfx ccm_dl_Wood_007_mesh[];
extern Gfx ccm_dl_Wood_008_mesh[];
extern Gfx ccm_dl_Wood_009_mesh[];
extern Gfx ccm_dl_material_revert_render_settings[];

