const GeoLayout wf_area_2_Level[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, -7685, 441, 3274, wf_Indoors_mesh),
				GEO_ANIMATED_PART(6, -7685, 441, 3274, wf_Indoors_001_mesh),
				GEO_ANIMATED_PART(1, -7685, 441, 3274, wf_Indoors_002_mesh),
				GEO_ANIMATED_PART(1, -15504, 604, 6238, wf_Indoors2_mesh),
				GEO_ANIMATED_PART(6, -1731, -4249, 2575, wf_Indoors2_001_mesh),
				GEO_ANIMATED_PART(1, -1731, -4249, 2575, wf_Indoors2_002_mesh),
				GEO_ANIMATED_PART(1, -1731, -4249, 2575, wf_Mines1_mesh),
				GEO_ANIMATED_PART(1, -1731, -4249, 2575, wf_Mines1_001_mesh),
				GEO_ANIMATED_PART(6, -1731, -4249, 2575, wf_Mines1_002_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wf_area_2_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -500, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, wf_area_2_Level),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_enfvx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, wf_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, wf_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
