const GeoLayout bob_area_4_Level[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, -252, -234, 12638, bob_Deathfloor_mesh),
				GEO_ANIMATED_PART(1, -252, -234, 12638, bob_MainPlat_mesh),
				GEO_ANIMATED_PART(1, -9227, -1442, 9842, bob_MainPlat_001_mesh),
				GEO_ANIMATED_PART(1, -1606, -1442, 13845, bob_MainPlat_002_mesh),
				GEO_ANIMATED_PART(1, -1772, -1442, 9153, bob_MainPlat_003_mesh),
				GEO_ANIMATED_PART(1, 1027, -1442, 8857, bob_MainPlat_004_mesh),
				GEO_ANIMATED_PART(1, -289, -2651, 10572, bob_RockPlat_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_4_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -500, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_4_Level),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_enfvx_main),
					GEO_ASM(0, geo_update_bob_light),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, bob_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, bob_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
