const GeoLayout canyon_elevator_geo[] = {
	GEO_CULLING_RADIUS(0x800),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, canyon_elevator_CanyonElevator_mesh),
		GEO_DISPLAY_LIST(0, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, canyon_elevator_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, canyon_elevator_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
