const GeoLayout jrb_area_1_root[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, jrb_visual_mesh),
				GEO_ANIMATED_PART(1, 0, 0, 0, jrb_visual_001_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_1_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(14, 0, 0, 0, 0, -500, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_1_root),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_enfvx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, jrb_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, jrb_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
